// import Footer from "@/Footer";
// import Header from "@/Header";
import * as React from "react";
import Header from "./Header";
import Footer from "./Footer";

// export const metadata = {
//   title: "Barun it solutions",
//   description: "Generated by core developers",
// };

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
